# This python script calculates a unique mail for a user

import sys
import subprocess
import string
import user
import re
# Getting the existing users of the system
existingUsers = [ ]
cutOutput = subprocess.Popen(["cut", "-d:","-f1", "/etc/passwd"], stdout=subprocess.PIPE).communicate()[0]
for name in cutOutput.split("\n"): 
    if not name.startswith("#"):
        try:
            existingUsers.append(user.User(name,name.rstrip('1234567890'),re.match('.*?([0-9]+)$', name).group(1)))
        except:
            existingUsers.append(user.User(name,name,0))

existingUsers = filter(None,existingUsers)

inputList = sys.stdin.readlines()
inputList = [name.lower() for name in inputList]

# Names are generated by taking the first three letters in the name followed by the two first from that last name
# a number is generated afterwards
inputList= filter(None,inputList)
inputList = [line for line in inputList if line.strip()]
toBeGeneratedUsernames = []
inputList = map(lambda s: s.strip('\n'), inputList)
inputList = map(lambda s: s.split(' '), inputList)
    
for name in inputList:
    if len(name) > 1:
        toBeGeneratedUsernames.append(user.User(str(name).replace(' ',':'), (name[0][:3] + name[1][:2]),0 ))
    else:
        toBeGeneratedUsernames.append(user.User(str(name),name[0][:5],0)) 
        
#Touchup
for users in toBeGeneratedUsernames:
    users.name = str(users.name).replace('[','').replace(']','').replace(',','').replace('\'', '')

generatedUsernames = [ ]
for i in range(0,len(toBeGeneratedUsernames)):
    for j in range(0,len(existingUsers)):
        if(toBeGeneratedUsernames[i].username == existingUsers[j].username and toBeGeneratedUsernames[i].number <= existingUsers[j].number ):
           	toBeGeneratedUsernames[i].number += int( existingUsers[j].number) + 1 

for i in range (0,len(toBeGeneratedUsernames)):
    for j in range (0, len(toBeGeneratedUsernames)):
        nmbr = 0
        while (i != j and toBeGeneratedUsernames[i].username == toBeGeneratedUsernames[j].username and ( toBeGeneratedUsernames[i].number <= toBeGeneratedUsernames[j].number )):
            toBeGeneratedUsernames[i].number += nmbr
            nmbr += 1
                
for user in toBeGeneratedUsernames:
    print user.name + ":"+ user.username + str(user.number) + "@example.com"


